openapi: 3.0.1
info:
  x-api-id: cb699e5c-f51f-4efb-8c8c-b8f6b48e115d
  title: Customer area API
  description: API for customer area
  version: 1.1.2
  contact:
    name: Lampros Papadimitriou
    email: lampros.papadimitriou@check24.de
  x-audience: component-internal
  license:
    name: MIT
servers:
  - url: https://api.trelobifteki.com/api/customer-area
paths:
  /customer-cases:
    get:
      summary: get all customer cases
      responses:
        '200':
          description: A paged array of customer cases
          content:
            application/json:
              schema:
                 $ref: "#/components/schemas/CustomerCases"
      security:
        - oauth2:
          - customer-cases.read
  /customer-cases/{customerCaseId}:
    get:
      summary: get customer case by id
      parameters:
        - name: customerCaseId
          in: path
          required: true
          description: The id of the customer case to retrieve
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Customer case
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CustomerCases"
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://identity.trelobifteki.com/oauth2/token
          scopes:
            customer-case-service.read: Access right needed to read from the customer case service.
  schemas:
    CustomerCase:
      description:
        Customer case including offers and agents assignments
      required:
        - id
        - name
      properties:
        id:
          type: string
        name:
          type: string
        metadata:
          description:
            Further metadata regarding customer case
          type: object
          additionalProperties:
            type: string
            description:
              further options
    CustomerCases:
      description:
        Customer cases related with the logged in user
      required:
        - cases
      properties:
        cases:
          type: array
          items:
            $ref: "#/components/schemas/CustomerCase"
